name: Downgraded Install

on:
    push:
        branches:
            - main

jobs:
    downgraded_install:
        runs-on: ubuntu-latest

        steps:
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.2
                    coverage: none

            -   run: composer require symfony/console:^4.4 --ansi

            # make co-exist with other dependencies
            -   run: composer require tomasvotruba/lines --ansi

            -   run: vendor/bin/lines --ansi
