name: Downgraded Release

on:
    push:
        branches:
            - main
        tags:
            # avoid infinite looping, skip tags that ends with ".72"
            # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-branches
            - '*'

jobs:
    downgrade_release:
        runs-on: ubuntu-latest

        steps:
            -   uses: "actions/checkout@v5"
                with:
                    token: ${{ secrets.WORKFLOWS_TOKEN || github.token }}

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.4
                    coverage: none

            # invoke patches
            -   run: composer install --ansi

            # but no dev packages
            -   run: composer update --no-dev --ansi

            # get rector to "rector-local" directory, to avoid downgrading itself in the /vendor
            -   run: mkdir rector-local
            -   run: composer require rector/rector --working-dir rector-local --ansi

            # downgrade to PHP 7.2
            -   run: rector-local/vendor/bin/rector process bin src vendor --config build/rector-downgrade-php-72.php --ansi

            # clear the dev files
            -   run: rm -rf tests ecs.php phpstan.neon phpunit.xml .gitignore .editorconfig

            # prefix and scope (inlined from prefix-code.sh)
            -
                run: |
                    export TERM=xterm-color

                    # download php-scoper
                    wget https://github.com/humbug/php-scoper/releases/download/0.18.3/php-scoper.phar -N --no-verbose

                    # scope the code, work around possible PHP memory limits
                    php -d memory_limit=-1 php-scoper.phar add-prefix bin src vendor composer.json --config scoper.php --force --ansi --output-dir scoped-code

                    # the output code is in "/scoped-code", move it up; local dirs must be empty to move easily
                    rm -r bin src vendor composer.json
                    mv scoped-code/* .

                    # dump composer autoload
                    composer dump-autoload --ansi --classmap-authoritative --no-dev

                    # make bin runnable without "php"
                    chmod 777 "bin/lines"
                    chmod 777 "bin/lines.php"

            # copy PHP 7.2 composer + workflows
            -   run: cp -r build/target-repository/. .

            # clear the dev files
            -   run: rm -rf build scoper.php rector.php php-scoper.phar rector-local

            # setup git user
            -
                working-directory: remote-repository
                run: |
                    git config user.email "tomas@getrector.org"
                    git config user.name "rector-bot"

            # publish to remote repository without tag
            -
                name: "Push Downgraded Code - branch"
                working-directory: remote-repository
                if: "!startsWith(github.ref, 'refs/tags/')"
                run: |
                    git add --all
                    git commit -m "Updated TypePerfect to commit ${{ github.event.after }}"
                    git push --quiet origin main

            # publish to remote repository with tag
            -
                name: "Push Downgraded Code - tag"
                working-directory: remote-repository
                if: "startsWith(github.ref, 'refs/tags/')"
                run: |
                    git add --all
                    git commit --allow-empty -m "TypePerfect ${GITHUB_REF#refs/tags/}"
                    git push --quiet origin main
                    git tag "${GITHUB_REF#refs/tags/}" -m "${GITHUB_REF#refs/tags/}"
                    git push --quiet origin "${GITHUB_REF#refs/tags/}"
